name: genefinder
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::samtools=1.20
  - bioconda::htslib=1.2.0
  - bioconda::sambamba=1.0.1
  - bioconda::pysamstats=1.1.2
  - bioconda::minimap2=2.28
  - bioconda::pyfaidx=0.8.1.1
  - conda-forge::pandas=2.2.2
  - conda-forge::lxml=5.2.2
  - conda-forge::numpy=1.26.4
